apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-api
spec:
  template:
    spec:
      containers:
        - name: sb-api
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
